import type { SearchResult } from "./search-api";

/**
 * Mock popular searches. In production this would come from an
 * analytics-backed endpoint (e.g. top-N symbols by search volume).
 */
const POPULAR_SEARCHES: SearchResult[] = [
  {
    symbol: "NDQ",
    display_name: "Betashares Nasdaq 100 ETF",
    kind: "etf",
    inception_date: "2015-05-26",
    currency: "AUD",
    domicile: "AU",
    exchange: "ASX",
    one_year_return: "32.15",
    five_year_return: "18.42",
    asset_classes: ["International Equities"],
    categories: ["Index"],
    asset_categories: ["International Equities"],
    trailing_12m_dividend_yield: "0.34",
    forward_12m_dividend_yield: "0.30",
    is_flagship_fund: true,
    flagship_description_short: "Nasdaq 100 ETF",
    flagship_image_url: null,
    discoverable_tags: ["technology", "nasdaq", "us equities"],
    classification: "International Equities",
    sub_classification: "North America",
    issuer: "Betashares",
    fund_size: "4200000000",
    management_fee: "0.48",
    dividend_frequency: "Semi-Annual",
    investment_suitability: "Capital growth",
    management_approach: "Passive",
    sector: null,
    market_capitalisation: null,
    pe_ratio_ttm: null,
    total_assets: null,
    total_revenue: null,
    quick_ratio: null,
    current_ratio: null,
    price_to_book_ratio: null,
  },
  {
    symbol: "A200",
    display_name: "Betashares Australia 200 ETF",
    kind: "etf",
    inception_date: "2018-05-07",
    currency: "AUD",
    domicile: "AU",
    exchange: "ASX",
    one_year_return: "14.20",
    five_year_return: "9.85",
    asset_classes: ["Australian Equities"],
    categories: ["Index"],
    asset_categories: ["Australian Equities"],
    trailing_12m_dividend_yield: "3.95",
    forward_12m_dividend_yield: "4.10",
    is_flagship_fund: true,
    flagship_description_short: "Australia 200 ETF",
    flagship_image_url: null,
    discoverable_tags: ["australian shares", "large cap", "asx 200"],
    classification: "Australian Equities",
    sub_classification: "Large Cap",
    issuer: "Betashares",
    fund_size: "5100000000",
    management_fee: "0.04",
    dividend_frequency: "Quarterly",
    investment_suitability: "Capital growth",
    management_approach: "Passive",
    sector: null,
    market_capitalisation: null,
    pe_ratio_ttm: null,
    total_assets: null,
    total_revenue: null,
    quick_ratio: null,
    current_ratio: null,
    price_to_book_ratio: null,
  },
  {
    symbol: "DHHF",
    display_name: "Betashares Diversified All Growth ETF",
    kind: "etf",
    inception_date: "2020-06-23",
    currency: "AUD",
    domicile: "AU",
    exchange: "ASX",
    one_year_return: "21.50",
    five_year_return: null,
    asset_classes: ["Multi-Asset"],
    categories: ["Diversified"],
    asset_categories: ["Multi-Asset"],
    trailing_12m_dividend_yield: "1.65",
    forward_12m_dividend_yield: "1.70",
    is_flagship_fund: true,
    flagship_description_short: "Diversified All Growth ETF",
    flagship_image_url: null,
    discoverable_tags: ["diversified", "all growth", "global"],
    classification: "Multi-Asset",
    sub_classification: "Growth",
    issuer: "Betashares",
    fund_size: "3200000000",
    management_fee: "0.19",
    dividend_frequency: "Semi-Annual",
    investment_suitability: "Capital growth",
    management_approach: "Passive",
    sector: null,
    market_capitalisation: null,
    pe_ratio_ttm: null,
    total_assets: null,
    total_revenue: null,
    quick_ratio: null,
    current_ratio: null,
    price_to_book_ratio: null,
  },
  {
    symbol: "HACK",
    display_name: "Betashares Global Cybersecurity ETF",
    kind: "etf",
    inception_date: "2018-08-31",
    currency: "AUD",
    domicile: "AU",
    exchange: "ASX",
    one_year_return: "18.75",
    five_year_return: "14.30",
    asset_classes: ["International Equities"],
    categories: ["Thematic"],
    asset_categories: ["International Equities"],
    trailing_12m_dividend_yield: "0.12",
    forward_12m_dividend_yield: "0.10",
    is_flagship_fund: false,
    flagship_description_short: null,
    flagship_image_url: null,
    discoverable_tags: ["cybersecurity", "technology", "thematic"],
    classification: "International Equities",
    sub_classification: "Thematic",
    issuer: "Betashares",
    fund_size: "980000000",
    management_fee: "0.67",
    dividend_frequency: "Semi-Annual",
    investment_suitability: "Capital growth",
    management_approach: "Passive",
    sector: null,
    market_capitalisation: null,
    pe_ratio_ttm: null,
    total_assets: null,
    total_revenue: null,
    quick_ratio: null,
    current_ratio: null,
    price_to_book_ratio: null,
  },
  {
    symbol: "ATEC",
    display_name: "Betashares S&P/ASX Australian Technology ETF",
    kind: "etf",
    inception_date: "2020-03-19",
    currency: "AUD",
    domicile: "AU",
    exchange: "ASX",
    one_year_return: "12.40",
    five_year_return: null,
    asset_classes: ["Australian Equities"],
    categories: ["Thematic"],
    asset_categories: ["Australian Equities"],
    trailing_12m_dividend_yield: "0.85",
    forward_12m_dividend_yield: "0.90",
    is_flagship_fund: false,
    flagship_description_short: null,
    flagship_image_url: null,
    discoverable_tags: ["technology", "australian tech", "thematic"],
    classification: "Australian Equities",
    sub_classification: "Thematic",
    issuer: "Betashares",
    fund_size: "450000000",
    management_fee: "0.48",
    dividend_frequency: "Semi-Annual",
    investment_suitability: "Capital growth",
    management_approach: "Passive",
    sector: null,
    market_capitalisation: null,
    pe_ratio_ttm: null,
    total_assets: null,
    total_revenue: null,
    quick_ratio: null,
    current_ratio: null,
    price_to_book_ratio: null,
  },
  {
    symbol: "AAA",
    display_name: "Betashares Australian High Interest Cash ETF",
    kind: "etf",
    inception_date: "2012-03-12",
    currency: "AUD",
    domicile: "AU",
    exchange: "ASX",
    one_year_return: "4.35",
    five_year_return: "2.10",
    asset_classes: ["Cash"],
    categories: ["Cash"],
    asset_categories: ["Cash and Equivalents"],
    trailing_12m_dividend_yield: "4.30",
    forward_12m_dividend_yield: "4.25",
    is_flagship_fund: true,
    flagship_description_short: "High Interest Cash ETF",
    flagship_image_url: null,
    discoverable_tags: ["cash", "high interest", "income"],
    classification: "Cash",
    sub_classification: "Cash",
    issuer: "Betashares",
    fund_size: "6800000000",
    management_fee: "0.18",
    dividend_frequency: "Monthly",
    investment_suitability: "Regular income",
    management_approach: "Active",
    sector: null,
    market_capitalisation: null,
    pe_ratio_ttm: null,
    total_assets: null,
    total_revenue: null,
    quick_ratio: null,
    current_ratio: null,
    price_to_book_ratio: null,
  },
];

/**
 * Returns mock popular searches. The async signature mirrors a future
 * real API call, making the swap trivial later.
 */
export async function getPopularSearches(): Promise<SearchResult[]> {
  return POPULAR_SEARCHES;
}
